import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProvider from "@/lib/ClientProvider";
import Head from "next/head";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Morning Light Planner",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <Head>
            {/* Preload fonts for hydration consistency */}
            <link
                rel="preload"
                href="/fonts/GeistVF.woff"
                as="font"
                type="font/woff"
                crossOrigin="anonymous"
            />
            <link
                rel="preload"
                href="/fonts/GeistMonoVF.woff"
                as="font"
                type="font/woff"
                crossOrigin="anonymous"
            />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        </Head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}>
            <ClientProvider>{children}</ClientProvider>
        </body>
        </html>
    );
}