import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProvider from "@/lib/ClientProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Morning Light Planner",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//     // for SSR, reinitialize Apollo client
//     const apolloClient = useApollo(null);
//
//     return (
//         <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//       <ApolloProvider client={apolloClient}>{children}</ApolloProvider>
//       </body>
//     </html>
//     );
// }
//

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            {/*<ApolloProvider client={apolloClient}>{children}</ApolloProvider>*/}
        <ClientProvider>{children}</ClientProvider>
        </body>
        </html>
    );
}
